### ISSUE TITLE
Cant start with --net=host

### ISSUE THREAD

**Issue by jokin** [streamsets/datacollector-docker#12]
Doesn't start connected to host network, when using the bridge network works well, but I can't connect to the host machine. 

2018-02-23 20:06:13,921 [user:] [pipeline:] [runner:] [thread:main] WARN  AbstractTask - Task 'stageLibrary' failed to initialize, java.lang.RuntimeException: Could not load runtime configuration, 'java.net.UnknownHostException: streamsets: streamsets: System error', calling stopTask() and going into ERROR
java.lang.RuntimeException: Could not load runtime configuration, 'java.net.UnknownHostException: streamsets: streamsets: System error'
at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.loadStages(ClassLoaderStageLibraryTask.java:406)
at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.initTask(ClassLoaderStageLibraryTask.java:225)
at com.streamsets.datacollector.task.AbstractTask.init(AbstractTask.java:62)
at com.streamsets.datacollector.task.CompositeTask.initTask(CompositeTask.java:44)
at com.streamsets.datacollector.task.AbstractTask.init(AbstractTask.java:62)
at com.streamsets.datacollector.task.TaskWrapper.init(TaskWrapper.java:40)
at com.streamsets.datacollector.main.Main.lambda$doMain$1(Main.java:108)
at java.security.AccessController.doPrivileged(Native Method)
at com.streamsets.datacollector.security.SecurityUtil.doAs(SecurityUtil.java:92)
at com.streamsets.datacollector.main.Main.doMain(Main.java:143)
at com.streamsets.datacollector.main.DataCollectorMain.main(DataCollectorMain.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.streamsets.pipeline.BootstrapMain.main(BootstrapMain.java:307)
Caused by: java.net.UnknownHostException: streamsets: streamsets: System error
at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
at com.streamsets.datacollector.el.RuntimeEL.loadRuntimeConfiguration(RuntimeEL.java:155)
at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.loadStages(ClassLoaderStageLibraryTask.java:402)
... 15 more
Caused by: java.net.UnknownHostException: streamsets: System error
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
... 17 more

**Comment by sureshkmit** [comment]
I'm also facing the same issue when running on AWS inside container.

**Comment by sureshkmit** [comment]
> Doesn't start connected to host network, when using the bridge network works well, but I can't connect to the host machine.
> 
> 2018-02-23 20:06:13,921 [user:] [pipeline:] [runner:] [thread:main] WARN AbstractTask - Task 'stageLibrary' failed to initialize, java.lang.RuntimeException: Could not load runtime configuration, 'java.net.UnknownHostException: streamsets: streamsets: System error', calling stopTask() and going into ERROR
> java.lang.RuntimeException: Could not load runtime configuration, 'java.net.UnknownHostException: streamsets: streamsets: System error'
> at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.loadStages(ClassLoaderStageLibraryTask.java:406)
> at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.initTask(ClassLoaderStageLibraryTask.java:225)
> at com.streamsets.datacollector.task.AbstractTask.init(AbstractTask.java:62)
> at com.streamsets.datacollector.task.CompositeTask.initTask(CompositeTask.java:44)
> at com.streamsets.datacollector.task.AbstractTask.init(AbstractTask.java:62)
> at com.streamsets.datacollector.task.TaskWrapper.init(TaskWrapper.java:40)
> at com.streamsets.datacollector.main.Main.lambda$doMain$1(Main.java:108)
> at java.security.AccessController.doPrivileged(Native Method)
> at com.streamsets.datacollector.security.SecurityUtil.doAs(SecurityUtil.java:92)
> at com.streamsets.datacollector.main.Main.doMain(Main.java:143)
> at com.streamsets.datacollector.main.DataCollectorMain.main(DataCollectorMain.java:55)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.streamsets.pipeline.BootstrapMain.main(BootstrapMain.java:307)
> Caused by: java.net.UnknownHostException: streamsets: streamsets: System error
> at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
> at com.streamsets.datacollector.el.RuntimeEL.loadRuntimeConfiguration(RuntimeEL.java:155)
> at com.streamsets.datacollector.stagelibrary.ClassLoaderStageLibraryTask.loadStages(ClassLoaderStageLibraryTask.java:402)
> ... 15 more
> Caused by: java.net.UnknownHostException: streamsets: System error
> at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
> at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
> at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
> at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
> ... 17 more

Hi @jokin did find any workaround for this issue?
