### ISSUE TITLE
InfluxDB corrupted destination

### ISSUE THREAD

**Issue by canimus** [streamsets/datacollector-docker#16]
### Configuration
Changed the extension to `.log` instead of `.json` to upload here.
[Windows to Kafka.log](https://github.com/streamsets/datacollector-docker/files/2324742/Windows.to.Kafka.log)

```sh
bash-4.3$ ls -ltra
total 8
drwxr-xr-x    7 uucp     143            166 Mar 12 17:49 jdk1.8.0_161
lrwxrwxrwx    1 root     root            17 Mar 12 17:49 jdk -> /opt/jdk1.8.0_161
drwxr-xr-x    2 sdc      sdc             20 Mar 12 17:49 streamsets-datacollector-user-libs
drwxr-xr-x   19 root     root          4096 Apr 18 07:35 streamsets-datacollector-3.1.1.0
drwxr-xr-x    5 root     root           119 Apr 18 07:35 .
drwxr-xr-x   23 root     root          4096 Aug 21 08:39 ..
```

I have a pipeline that received JSON formatted messages from Kafka, and place them into an InfluxDB database. In the pipeline there are the following processors:

- Input:Kafka Consumer
- Processor: Expression Evaluator
- Processor: File Type Converter
- Processor: File Remover
- Processor: File Renamer
- Processor: Stream Selector
- Destination: Trash
- Destination: InfluxDB (Stage Library 0.9+)

`InfluxDB version 1.5.1`

### Unexpected Behaviour
> InfluxDB database shows an invalid __measurement__ and truncated values. The exception is leaking some information to the InfluxDB destination even when the criteria in the pipeline states otherwise.

### Payload
```json
{
  "EventReceivedTime": "2018-08-24 16:04:25.585545+02:00",
  "date": "2018-07-30",
  "time": "16:30:56",
  "sip": "1.1.1.1",
  "csmethod": "GET",
  "csuristem": "/webapplication/WebForms/Beheer/Authorisatie/Dialogs/MedewerkerDialog.aspx",
  "sport": "80",
  "csusername": "EUROPE\nxx-strong-pos1",
  "cip": "2.2.2.2",
  "scstatus": "200",
  "scsubstatus": "0",
  "scwin32status": "0",
  "timetaken": "62",
  "host": "XXX",
  "environment": "a1"
}
# IPs and values are ofuscated
```

### Error Log
`/logs`
```sh
java.lang.RuntimeException: {"error":"partial write: unable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields\nunable to parse 'iis_log,cip=10.197.11.31,csusername=EUROPE': missing fields dropped=0"}

        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
        at org.influxdb.impl.$Proxy85.writePoints(Unknown Source)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:161)
        at com.streamsets.pipeline.stage.destination.influxdb.InfluxTarget.write(InfluxTarget.java:102)
        at com.streamsets.pipeline.configurablestage.DTarget.write(DTarget.java:34)
        at com.streamsets.datacollector.runner.StageRuntime$2.call(StageRuntime.java:252)
        at com.streamsets.datacollector.runner.StageRuntime$2.call(StageRuntime.java:236)
        at com.streamsets.datacollector.runner.StageRuntime.execute(StageRuntime.java:194)
        at com.streamsets.datacollector.runner.StageRuntime.execute(StageRuntime.java:263)
        at com.streamsets.datacollector.runner.StagePipe.process(StagePipe.java:225)
        at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.processPipe(ProductionPipelineRunner.java:760)
        at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.lambda$runSourceLessBatch$3(ProductionPipelineRunner.java:788)
        at com.streamsets.datacollector.runner.PipeRunner.executeBatch(PipeRunner.java:132)
        at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.runSourceLessBatch(ProductionPipelineRunner.java:787)
        at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunner.processBatch(ProductionPipelineRunner.java:468)
        at com.streamsets.datacollector.runner.StageRuntime$4.run(StageRuntime.java:327)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.streamsets.datacollector.runner.StageRuntime.processBatch(StageRuntime.java:323)
        at com.streamsets.datacollector.runner.StageContext.processBatch(StageContext.java:241)
        at com.streamsets.pipeline.lib.dirspooler.SpoolDirRunnable.produce(SpoolDirRunnable.java:303)
        at com.streamsets.pipeline.lib.dirspooler.SpoolDirRunnable.run(SpoolDirRunnable.java:152)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:227)
        at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:33)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:223)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeRunnable.run(SafeScheduledExecutorService.java:189)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:227)
        at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:33)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:223)
        at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeRunnable.run(SafeScheduledExecutorService.java:189)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-08-27 15:59:12,971 [user:admin] [pipeline:Windows to Kafkacopy/WindowstoKafkacopy4ee5f4f1-5e3b-4257-86e0-e044c3e8dea8] [runner:] [thread:webserver-1264] INFO  StandaloneRunner - Preparing to stop pipeline
2018-08-27 15:59:12,985 [user:*admin] [pipeline:Windows to Kafkacopy/WindowstoKafkacopy4ee5f4f1-5e3b-4257-86e0-e044c3e8dea8] [runner:] [thread:runnerStop-pool-10-thread-4] INFO  StandaloneRunner - Stopping pipeline WindowstoKafkacopy4ee5f4f1-5e3b-4257-86e0-e044c3e8dea8 0

```

**Comment by dimaspivak** [comment]
Hi @canimus, this repo is for the Data Collector Dockerfile only, but please open a JIRA at issues.streamsets.com and we'll be able to look into this. Thanks!

**Comment by canimus** [comment]
Thanks @dimaspivak. I have created the Jira ticket with number [SDC-9888](https://issues.streamsets.com/browse/SDC-9888) for anyone interested.
